### ISSUE TITLE
Can not found  githubtimeline.xyz  IP address

### ISSUE THREAD

**Issue by QGB** [barisesen/github-timeline#11]
无法访问此网站
找不到 githubtimeline.xyz 的服务器 IP 地址。
尝试运行 Windows 网络诊断。
DNS_PROBE_FINISHED_NXDOMAIN

This site can't be reached server IP address could not be found.

**Comment by barisesen** [comment]
Thank you for your return. You cannot view the domain name because it has expired. Now you can access it at https://barisesen.github.io/github-timeline/.
