### ISSUE TITLE
shows incorrect

### ISSUE THREAD

**Issue by boratanrikulu** [barisesen/github-timeline#5]
It shows some information incorrect like as following.

![screenshot_2018-10-08_01-18-20](https://user-images.githubusercontent.com/20258973/46587651-0145ee00-ca98-11e8-81fa-d27f839bc745.png)

**Comment by barisesen** [comment]
This is probably because the pull request event is not added.
Maybe you can add it for us @boratanrikulu

**Comment by boratanrikulu** [comment]
I added pull request event. https://github.com/barisesen/github-timeline/pull/6

But still there is a issue. 

**pausiber.github.io** is not a new repository as in the screenshot. I don't figure out what's causing it.
